import type { Metadata } from "next";


import { Providers } from "@/providers/Providers";

import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";

import '../styles/reset.css';
import '../styles/global.css';
import { allCategory } from "@/services/allCategory";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const categorie = await allCategory();


  return (
    <html lang="en">
      <body className="flex flex-col">
        <Providers>
          <Header categorie={categorie} />
              <main className="flex flex-1">{children}</main>
          <Footer />
        </Providers>
          
        
      </body>
    </html>
  );
}
