
import type { Metadata } from "next";

import Header from "./_components/header/Header";
import Footer from "./_components/footer/Footer";

import { ProductProvider } from "./context/useProductContext";
import { allCategory } from "./services/allCategory";

import "./globals.css";
import "./reset.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const categorie = await allCategory();


  return (
    <html lang="en">
      <body className="flex flex-col">
        
          <Header categorie={categorie} />
            <ProductProvider > 
              <main className="flex-1">{children}</main>
            </ProductProvider>
          <Footer />
        
      </body>
    </html>
  );
}
